#!/bin/sh

set -eu

cp env.sh-encrypted env.sh-decrypting
ansible-vault decrypt env.sh-decrypting
mv env.sh-decrypting env.sh

cp env-encrypted env-decrypting
ansible-vault decrypt env-decrypting
mv env-decrypting env
